#!/bin/sh
### BEGIN INIT INFO
# Provides:          gcpcsp
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Google Cloud SQL Proxy
### END INIT INFO

SCRIPT=/opt/gcpcsp/cloud_sql_proxy
RUNAS=root

APP_ETC=/etc/gcpcsp/
APP_CONFIG=$APP_ETC/gcpcsp.conf

# Load application config
. $APP_CONFIG

if [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
  OPTIONS="-instances=$INSTANCE_ID=tcp:$DB_PORT $ADDITIONAL_OPTIONS"
else
  OPTIONS="-instances=$INSTANCE_ID=tcp:$DB_PORT -credential_file=$GOOGLE_APPLICATION_CREDENTIALS $ADDITIONAL_OPTIONS"
fi

PIDFILE=/var/run/gcpcsp.pid
LOGFILE=/var/log/gcpcsp.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT $OPTIONS &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is NOT removed: '$LOGFILE'" >&2
    update-rc.d -f gcpcsp remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
